name: GitHub Actions CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TEST_ORGANIZATION: 'kfcampbell-terraform-provider'
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: make tools
      - run: make lint
      - run: make website-lint
      - run: make build
      - run: make test

  tests:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        tests: [stack_01] # name of test folder in ./tests/. Extend as needed.
    
    defaults:
      run:
        working-directory: ./tests/${{ matrix.tests }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build provider
        run: go build -o terraform-provider-github

      - name: Setup dev overrides
        run: |
          mkdir -p ~/.terraformrc
          cat > ~/.terraformrc << 'EOF'
          provider_installation {
            dev_overrides {
              "integrations/github" = "$(pwd)"
            }
            direct {}
          }
          EOF

      - name: Test with terraform (this should NOT fail with SDK validation errors)
        run: |
          terraform init || echo "Init failed - expected for dev overrides"
          terraform validate
